Repository frosty-dev/ss14-wwdp, pull requests merged in 2024-08, with the labels that each got.

#16 Телескоп
  Content.Client/Input/ContentContexts.cs
  Content.Client/Options/UI/Tabs/KeyRebindTab.xaml.cs
  Content.Client/_White/Telescope/TelescopeSystem.cs
  Content.Server/GameTicking/GameTicker.Spawning.cs
  Content.Server/_White/Telescope/TelescopeSystem.cs
  Content.Shared/Input/ContentKeyFunctions.cs
  Content.Shared/_White/Telescope/SharedTelescopeSystem.cs
  Content.Shared/_White/Telescope/TelescopeComponent.cs
  Resources/Locale/en-US/_white/escape-menu/options-menu.ftl
  Resources/Locale/ru-RU/_white/escape-menu/options-menu.ftl
  Resources/Locale/ru-RU/round-end/round-end-summary-window.ftl
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
  Resources/Prototypes/Voice/speech_emotes.yml
  Resources/keybinds.yml
Labels: 🌱 Ready to merge, 🍺 Review requested, Type: Port, Changes: C#, Changes: Localization, Changes: UI, Changes: YML, Status: Needs Review

#14 Updating license wording
  README.md
Labels: Status: Needs Review, Changes: Documentation

#28 Обновление Readme
  README.md
Labels: Type: Feature, Changes: Documentation

#30 [Fix] Исправления для RSI тестов.
  Resources/Textures/White/Charge/charge.rsi/meta.json
  Resources/Textures/White/Clothing/Eyes/Glasses/nightvision.rsi/meta.json
  Resources/Textures/White/Clothing/Head/cage-equipped.rsi/equipped-HELMET.png
  Resources/Textures/White/Clothing/Head/cage-equipped.rsi/meta.json
  Resources/Textures/White/Clothing/Head/cage.rsi/meta.json
  Resources/Textures/White/Clothing/Head/wizhat.rsi/icon 2.png
  Resources/Textures/White/Fluff/6elblu/white-overcoat.rsi/meta.json
  Resources/Textures/White/Fluff/thechaotic/coat.rsi/meta.json
  Resources/Textures/White/Ghosts/aeons_torn-ghost.rsi/meta.json
  Resources/Textures/White/Ghosts/ravmorgan-ghost.rsi/meta.json
  Resources/Textures/White/Ghosts/scituzer2-ghost.rsi/meta.json
  Resources/Textures/White/Ghosts/valtos-ghost.rsi/meta.json
  Resources/Textures/White/Interface/securityhud.rsi/meta.json
  Resources/Textures/White/Misc/scrolls.rsi/meta.json
  Resources/Textures/White/Mobs/Customization/imercuryi.rsi/meta.json
  Resources/Textures/White/Objects/Weapons/Guns/Rifles/ak-icons.rsi/meta.json
  Resources/Textures/White/Objects/Weapons/Guns/Rifles/lecter-icons.rsi/meta.json
  Resources/Textures/White/Objects/Weapons/Guns/SMG/atreides-icons.rsi/meta.json
  Resources/Textures/White/Objects/Weapons/Guns/SMG/c20r-icons.rsi/meta.json
  Resources/Textures/White/Objects/Weapons/Guns/SMG/drozd-icons.rsi/meta.json
  Resources/Textures/White/Objects/Weapons/Guns/SMG/wt550-icons.rsi/meta.json
  Resources/Textures/White/Objects/Weapons/Guns/Snipers/bolt_gun_wood-icons.rsi/meta.json
  Resources/Textures/White/Objects/Weapons/Throwable/energybola.rsi/meta.json
Labels: Type: Fix, Changes: Sprite

#12 Аспекты!
  Content.Server/GameTicking/Rules/TraitorRuleSystem.cs
  Content.Server/Holiday/Christmas/RandomGiftSystem.cs
  Content.Server/_White/AspectsSystem/Aspects/Components/ImmersiveAspectComponent.cs
  Content.Server/_White/AspectsSystem/Aspects/Components/LandmineAspectComponent.cs
  Content.Server/_White/AspectsSystem/Aspects/Components/NothingAspectComponent.cs
  Content.Server/_White/AspectsSystem/Aspects/Components/PresentAspectComponent.cs
  Content.Server/_White/AspectsSystem/Aspects/Components/ReflectAspectComponent.cs
  Content.Server/_White/AspectsSystem/Aspects/Components/TraitorRichAspectComponent.cs
  Content.Server/_White/AspectsSystem/Aspects/Components/TraitoredAspectComponent.cs
  Content.Server/_White/AspectsSystem/Aspects/ImmersiveAspect.cs
  Content.Server/_White/AspectsSystem/Aspects/LandmineAspect.cs
  Content.Server/_White/AspectsSystem/Aspects/NothingAspect.cs
  Content.Server/_White/AspectsSystem/Aspects/PresentAspect.cs
  Content.Server/_White/AspectsSystem/Aspects/ReflectAspect.cs
  Content.Server/_White/AspectsSystem/Aspects/TraitorRichAspect.cs
  Content.Server/_White/AspectsSystem/Aspects/TraitoredAspect.cs
  Content.Server/_White/AspectsSystem/Base/AspectComponent.cs
  Content.Server/_White/AspectsSystem/Base/AspectSystem.cs
  Content.Server/_White/AspectsSystem/Commands/AspectCommands.cs
  Content.Server/_White/AspectsSystem/Managers/AspectManager.cs
  Content.Server/_White/Other/GiftIgnoreComponent.cs
  Content.Server/_White/Other/ReflectAspectMarkComponent.cs
  Content.Shared.Database/LogType.cs
  Content.Shared/_White/CVars.cs
  Resources/Audio/_White/Aspects/accent.ogg
  Resources/Audio/_White/Aspects/attributions.yml
  Resources/Audio/_White/Aspects/palevo.ogg
  Resources/Locale/en-US/_white/aspects/aspects.ftl
  Resources/Locale/ru-RU/_white/aspects/aspects-entity.ftl
  Resources/Locale/ru-RU/_white/aspects/aspects.ftl
  Resources/Prototypes/Entities/Clothing/OuterClothing/armor.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/Entities/Debugging/debug_sweps.yml
  Resources/Prototypes/Entities/Objects/Devices/station_beacon.yml
  Resources/Prototypes/Entities/Objects/Misc/implanters.yml
  Resources/Prototypes/Entities/Objects/Specific/syndicate.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Launchers/launchers.yml
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_assembly.yml
  Resources/Prototypes/Entities/Structures/Doors/MaterialDoors/material_doors.yml
  Resources/Prototypes/Entities/Structures/base_structure.yml
  Resources/Prototypes/_White/Aspects/Aspects.yml
  Resources/Prototypes/_White/Aspects/AspectsEntity.yml
Labels: Type: Port, Changes: C#, Changes: Localization, Changes: YML, Changes: Audio, Status: Needs Review
